// Generates lib/localstack-config.ts from the CDK deploy outputs (cdk-outputs.json).
// Usage: node scripts/gen-config.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outputs = JSON.parse(readFileSync(join(root, "cdk-outputs.json"), "utf8"));
const stacks = Object.keys(outputs);
if (stacks.length !== 1) {
  throw new Error(`expected exactly one deployed stack, got: ${stacks.join(", ")}`);
}
const o = outputs[stacks[0]];
const region = o.UserPoolId.split("_")[0];

const content = `// Generated by scripts/gen-config.mjs from cdk-outputs.json — do not edit by hand.
export const localstackConfig = {
  stackName: ${JSON.stringify(stacks[0])},
  region: ${JSON.stringify(region)},
  userPoolId: ${JSON.stringify(o.UserPoolId)},
  userPoolClientId: ${JSON.stringify(o.UserPoolClientId)},
  apiId: ${JSON.stringify(o.ApiId)},
  stageName: ${JSON.stringify(o.StageName)},
  // Same-origin prefixes proxied to LocalStack by next.config.ts rewrites, so the
  // browser never makes a cross-origin call (CORS-free, works on any dev port).
  cognitoPrefix: "/ls-cognito",
  apiPrefix: "/ls-api",
} as const;
`;
writeFileSync(join(root, "lib/localstack-config.ts"), content);
console.log(`wrote lib/localstack-config.ts for stack ${stacks[0]}`);
