# LocalStack Resource Provider Scaffolding v2
from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import TypedDict

from botocore.exceptions import ClientError

import localstack.services.cloudformation.provider_utils as util
from localstack.services.cloudformation.resource_provider import (
    OperationStatus,
    ProgressEvent,
    ResourceProvider,
    ResourceRequest,
)
from localstack.services.sns.provider import create_default_topic_policy


class SNSTopicPolicyProperties(TypedDict):
    PolicyDocument: dict | str | None
    Topics: list[str] | None
    Id: str | None


REPEATED_INVOCATION = "repeated_invocation"


def _serialize_policy(policy: dict | str) -> str:
    if isinstance(policy, str):
        return policy
    return json.dumps(policy)


def _is_not_found(error: ClientError) -> bool:
    return "NotFound" in error.response.get("Error", {}).get("Code", "")


def _restore_default_policy(sns_client, topic_arn: str) -> None:
    try:
        sns_client.set_topic_attributes(
            TopicArn=topic_arn,
            AttributeName="Policy",
            AttributeValue=create_default_topic_policy(topic_arn),
        )
    except ClientError as error:
        if not _is_not_found(error):
            raise


class SNSTopicPolicyProvider(ResourceProvider[SNSTopicPolicyProperties]):
    TYPE = "AWS::SNS::TopicPolicy"  # Autogenerated. Don't change
    SCHEMA = util.get_schema_path(Path(__file__))  # Autogenerated. Don't change

    def create(
        self,
        request: ResourceRequest[SNSTopicPolicyProperties],
    ) -> ProgressEvent[SNSTopicPolicyProperties]:
        """
        Create a new resource.

        Primary identifier fields:
          - /properties/Id

        Required properties:
          - PolicyDocument
          - Topics

        Read-only properties:
          - /properties/Id

        IAM permissions required:
          - sns:SetTopicAttributes

        """
        model = copy.deepcopy(request.desired_state)
        sns_client = request.aws_client_factory.sns

        policy = _serialize_policy(model["PolicyDocument"])
        for topic_arn in model["Topics"]:
            sns_client.set_topic_attributes(
                TopicArn=topic_arn, AttributeName="Policy", AttributeValue=policy
            )

        model["Id"] = util.generate_default_name(
            stack_name=request.stack_name, logical_resource_id=request.logical_resource_id
        )

        return ProgressEvent(
            status=OperationStatus.SUCCESS,
            resource_model=model,
            custom_context=request.custom_context,
        )

    def read(
        self,
        request: ResourceRequest[SNSTopicPolicyProperties],
    ) -> ProgressEvent[SNSTopicPolicyProperties]:
        """
        Fetch resource information


        """
        raise NotImplementedError

    def delete(
        self,
        request: ResourceRequest[SNSTopicPolicyProperties],
    ) -> ProgressEvent[SNSTopicPolicyProperties]:
        """
        Delete a resource

        IAM permissions required:
          - sns:SetTopicAttributes
        """
        model = request.previous_state
        sns = request.aws_client_factory.sns

        for topic_arn in model["Topics"]:
            _restore_default_policy(sns, topic_arn)

        return ProgressEvent(
            status=OperationStatus.SUCCESS,
            resource_model={},
            custom_context=request.custom_context,
        )

    def update(
        self,
        request: ResourceRequest[SNSTopicPolicyProperties],
    ) -> ProgressEvent[SNSTopicPolicyProperties]:
        """
        Update a resource

        IAM permissions required:
          - sns:SetTopicAttributes
        """
        model = copy.deepcopy(request.desired_state)
        previous_model = request.previous_state
        sns = request.aws_client_factory.sns

        policy = _serialize_policy(model["PolicyDocument"])
        for topic_arn in model["Topics"]:
            sns.set_topic_attributes(
                TopicArn=topic_arn,
                AttributeName="Policy",
                AttributeValue=policy,
            )

        desired_topics = set(model["Topics"])
        for topic_arn in previous_model.get("Topics", []):
            if topic_arn not in desired_topics:
                _restore_default_policy(sns, topic_arn)

        model["Id"] = previous_model["Id"]
        return ProgressEvent(
            status=OperationStatus.SUCCESS,
            resource_model=model,
            custom_context=request.custom_context,
        )
